### ISSUE TITLE
Decoration for drawer

### ISSUE THREAD

**Issue by alejandrogiubel** [rododendron88/flutter_drawer_menu#1]
Hi, great plugin. Overscroll is what I am looking for. Would be nice add decoration feature for drawer. I need to do rounded borders. Thanks in advance.

**Comment by rododendron88** [comment]
Hi. I added the necessary property for decorating the menu in version 0.1.2. Please check the example.

**Comment by rododendron88** [comment]
menuOverlapWidth - width of the menu overlay above the body. This setting is useful for menu decoration. Default is 0.
